cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/<int:option_id>', remove, name='product_remove'),
]

members/urls.py
from django.contrib import admin
from django.urls import path
from members.views import *
from django.urls import re_path
from .views import *
from coupon.views import coupon


app_name = 'members'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    #path('signup/', send_and_confirm, name='send_and_confirm'),

    #path('signup/', sms_send, name='sms_send'),
    #path('login/', login, name='login'),
    #path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('mypage/', mypage, name='mypage'),
    path('mypage/coupon', coupon, name="coupon"),
    path('test/', send_and_confirm, name='test'),
    path('mypage/address', address, name="address"),
    path('mypage/address/add', add_address, name="add_address"),
    path('mypage/address/<int:id>/update', update_address, name="update_address"),
    path('mypage/address/<int:id>/delete', delete_address, name="delete_address"),
    path('profile/delete', delete, name='delete'),
    path('mypage/order', order, name='order'),
    path('mypage/order/<orderno>/', order_detail, name="order_detail"),
    path('findID/', findID, name='findID'),

    #path('admin/', admin.site.urls), # 이유진
]

order/urls.py
from django.urls import path
from .views import *
from django.contrib import admin
from members.views import *
from django.urls import re_path


app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(), name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(), name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(), name='order_validation'),
    path('complete/', order_complete, name='order_complete'),
    path('admin/<int:order_id>/', admin_order_detail, name='admin_order_detail')

]

members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser # 유진이
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.conf import settings
from .CertiNum import get_centification_number

# Create your models here.

#class User(AbstractUser):
#    mileage = models.IntegerField(default=0)
#    coupon = models.ManyToManyField(Coupon)


class UserManager(BaseUserManager):
    def _create_user(self, email, password):
        email = self.normalize_email(email)
        user = self.model(email=email)
        user.set_password(password)
        user.save()
        #Phone.objects.create(user=user)
        return user

    def create_user(self, email, password=None):
        return self._create_user(email, password)


class Marketing(models.Model):
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name


class SmsSend(models.Model):
    MSG_TYPE_CHOICES = (
        ('sms', 'sms'),
    )
    msg_type = models.CharField(max_length=3, choices=MSG_TYPE_CHOICES, default='sms')
    # IntegerField로 하면 휴대폰 전화번호 첫자리 '0' 이 사라진다.
    msg_getter = models.CharField(max_length=20, blank=False)
    msg_sender = models.CharField(max_length=20, blank=False, default=settings.SENDER)
    msg_text = models.CharField(max_length=4)

    def __str__(self):
        return self.msg_text


class User(AbstractUser): # 원래는 AbstractBaseUser
    name = models.CharField(max_length=20)
    mileage = models.IntegerField(default=0)
    #coupon = models.ManyToManyField(Coupon)
    #email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    #USERNAME_FIELD = 'email'
    marketing = models.ManyToManyField(Marketing, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    sex = models.CharField(max_length=10, null=True, blank=True)
    objects = UserManager()


class Address(models.Model):
    addr_name = models.CharField(max_length=30)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    zip = models.CharField(max_length=20)
    addr1 = models.CharField(max_length=250)
    addr2 = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)

coupon/forms.py
from django import forms
from coupon.models import CouponUser, Coupon
from order.models import Order

class RegisterCouponForm(forms.ModelForm):
    input_code = forms.CharField(max_length=20)
    class Meta:
        model = CouponUser
        fields = ['input_code']


'''class SelectCouponForm(forms.Form):
    coupon = forms.ModelChoiceField(queryset=CouponUser.objects.none())

    class Meta:
        model = Order
        fields = ['coupon']

    def __init__(self, user):
        super(SelectCouponForm, self).__init__()
        coupon_ids = CouponUser.objects.filter(user=user).values_list('coupon_id', flat=True)
        for id in coupon_ids:
            self.fields['coupon'].queryset = self.fields['coupon'].queryset | Coupon.objects.filter(id=id)'''

coupon/views.py
from django.shortcuts import render
from members.models import User
from .forms import RegisterCouponForm
from coupon.models import Coupon, CouponUser
from shop.models import Category
from django.utils import timezone
# Create your views here.

def valid(coupon_code, user):
    coupon_exist_valid = Coupon.objects.filter(code=coupon_code)
    if coupon_exist_valid == None:
        print("coupon doesnt exist")
        return False
    else:
        actual_coupon = coupon_exist_valid.first()
        already_registered_valid = CouponUser.objects.filter(coupon=actual_coupon, user=user)
        if len(already_registered_valid) == 0:
            if timezone.now() > actual_coupon.expiration_date:
                print("check coupon date")
                return False
            else:
                return True

        else:
            print("coupon already registered")
            return False

#쿠폰함/쿠폰등록
def coupon(request):
    categories = Category.objects.all()
    user = User.objects.get(id=request.user.id)
    form = RegisterCouponForm(request.POST)

    if form.is_valid():
        input_code = request.POST['input_code']
        v = valid(input_code, user)

        if v==True:
            actual_coupon = Coupon.objects.filter(code=input_code).first()
            new_coupon_user = CouponUser(user=user, coupon=actual_coupon, times_used=0)
            new_coupon_user.save()

    coupons = CouponUser.objects.filter(user=user, times_used=0)
    context = {'categories': categories, 'user': user, 'form': form, 'coupons':coupons}
    return render(request, 'members/coupon.html', context)

members/views.py
# Create your views here.
from random import randint
from django.contrib.auth import login as django_login, authenticate, logout as django_logout, get_user_model
from django.shortcuts import render, redirect,get_object_or_404
from sdk.api.message import Message
from sdk.exceptions import CoolsmsException
from django.conf import settings
from django.http import HttpResponse
from allauth.account.views import *
#from members.models import Phone

from .forms import *

from .models import SmsSend
from .CertiNum import get_centification_number
from members.models import *
from kwShop.forms import CustomSignupForm
#from django.shortcuts import render, get_object_or_404
from shop.models import Category
from coupon.models import *
import datetime
from order.models import *
from kwShop.forms import *
from django.http import HttpResponseRedirect
# Create your views here.

#User = settings.AUTH_USER_MODEL

# allauth customizing
class CustomSignupView(SignupView):
    #template_name = "members/signup." + app_settings.TEMPLATE_EXTENSION
    #form_class = CustomSignupForm

    success_url =  '/test/'

    def get_success_url(self):
        return '/test/'

    def send_and_confirm(request):
        send_form = SmsForm(data=request.POST)
        # confirm_form = ConfirmForm(request.POST)

        def get_valid_sms_info_and_save():
            get_valid_params = {
                'type': 'sms',
                'to': request.POST.get('msg_getter'),
                'from': settings.SENDER,
                'text': str(get_centification_number(4)),
            }
            send_form.save()
            return get_valid_params
        if request.method == "POST":
            confirm_form = ConfirmForm(request.POST)
            if send_form.is_valid():
                try:
                    params = get_valid_sms_info_and_save()
                    cool = Message(settings.COOLSMS_API_KEY, settings.COOLSMS_API_SECRET)
                    response = cool.send(params)
                    if 'error_list' in response:
                        print('Error List : {}'.format(response['error_list']))
                    return redirect('test')
                except CoolsmsException as e:
                    return HttpResponse('Error : {} - {}'.format(e.code, e.msg))
            if confirm_form.is_valid():
                try:
                    params2 = dict()
                    #params2['send_time'] = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
                    cool = Message(settings.COOLSMS_API_KEY, settings.COOLSMS_API_SECRET)
                    response2 = cool.sent(params2)
                    data = response2['data']
                    #print(data)
                    if request.POST.get('conf') == data[0]['text']:
                            return HttpResponseRedirect('/')
                except CoolsmsException as e:
                    return HttpResponse('Error : {} - {}'.format(e.code, e.msg))
        else:
            send_form = SmsForm()
            confirm_form = ConfirmForm()
        context = {
            'send_form': send_form,
            'confirm_form': confirm_form
        }
        return render(request, 'members/test.html', context)


signup = CustomSignupView.as_view()

# allauth customizing
def send_and_confirm(request):
    send_form = SmsForm(data=request.POST)

    # confirm_form = ConfirmForm(request.POST)

    def get_valid_sms_info_and_save():
        get_valid_params = {
            'type': 'sms',
            'to': request.POST.get('msg_getter'),
            'from': settings.SENDER,
            'text': str(get_centification_number(4)),
        }
        send_form.save()
        return get_valid_params

    if request.method == "POST":
        confirm_form = ConfirmForm(request.POST)
        if send_form.is_valid():
            try:
                params = get_valid_sms_info_and_save()
                cool = Message(settings.COOLSMS_API_KEY, settings.COOLSMS_API_SECRET)
                response = cool.send(params)
                '''
                success_count = response['success_count']
                print(success_count)
                error_count = response['error_count']
                print(error_count)
                print('Group ID : {}'.format(response['group_id']))
                '''
                if 'error_list' in response:
                    print('Error List : {}'.format(response['error_list']))
                return redirect('members:test')
            except CoolsmsException as e:
                return HttpResponse('Error : {} - {}'.format(e.code, e.msg))
        if confirm_form.is_valid():
            try:
                params2 = dict()
                # params2['send_time'] = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
                cool = Message(settings.COOLSMS_API_KEY, settings.COOLSMS_API_SECRET)
                response2 = cool.sent(params2)
                data = response2['data']
                # print(data)
                if request.POST.get('conf') == data[0]['text']:
                    return HttpResponse('okt')
            except CoolsmsException as e:
                return HttpResponse('Error : {} - {}'.format(e.code, e.msg))
    else:
        send_form = SmsForm()
        confirm_form = ConfirmForm()
    context = {
        'send_form': send_form,
        'confirm_form': confirm_form
    }
    return render(request, 'members/signup.html', context)
'''
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            User.objects.create_user(email=email, password=raw_password)
            user = authenticate(email=email, password=raw_password)
#            django_login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()


def login(request):
    if request.method == 'POST':
        form = LogInForm(request.POST)
        if form.is_valid():
            form.login(request)
            return redirect('index')
    else:
        form = LogInForm()
    return render(request, 'account/login.html', {'form': form})


def relogin(request):
    if request.method == 'POST':
        form = LogInForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.clean_verify_password()
            form.login(request)
            return redirect('index')
    else:
        form = LogInForm()
    return render(request, 'account/relogin.html', {'form': form})
'''

def index(request):
    return render(request, 'base.html')

def address(request):
    member = get_object_or_404(User, username=request.user)
    addresses = Address.objects.filter(username=request.user)


    return render(request, 'members/address.html', {'addresses':addresses})


def update_address(request, id):
    address = get_object_or_404(Address, id=id)

    if request.method == "POST":
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            return redirect('members:address')
    else:
        form = AddressForm(instance=address)

    return render(request, 'members/update_address.html', {'form': form})

def delete_address(request, id):
    address = get_object_or_404(Address, id=id)

    if request.method == "POST":
        address.delete()
        return redirect('members:address')
    else:
        return render(request, 'members/delete_address.html', {'object':address})


def add_address(request):
    member = get_object_or_404(User, username=request.user)
    if request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.username=request.user
            address.save()
            print (address)
            return redirect('members:address')
    else:
        form = AddressForm(instance=member)

    return render(request, 'members/add_address.html', {'form': form})


def order(request):
    try:
        member = get_object_or_404(User, username=request.user)
        orders = Order.objects.filter(order_userID=member, paid=True)
        for order in orders:
            orderitems = OrderItem.objects.filter(order=order)
        count=0
        for orderitem in orderitems:
            count+=1
        return render(request, 'members/order.html', {'orders':orders, 'orderitem':orderitems[0], 'count':count-1})
    except:
        return render(request, 'members/order.html', {'orders':None, 'orderitems':None})

def order_detail(request, orderno):
    order= get_object_or_404(Order, orderno=orderno)
    orderitems = OrderItem.objects.filter(order=order)
    print(orderitems)
    return render(request, 'members/order_detail.html',
                  {'order': order, 'orderitems': orderitems})


def findID(request):
    if request.method == "POST":
        form = findIDForm(request.POST or None)
        if form.is_valid():
            try :
                member = User.objects.get(name=form['name'].value(), phone=form['phone'].value())
                return render(request, 'members/confirmID.html', {'member':member})
            except:
                return render(request, 'members/wrongID.html')

    else:
        form = findIDForm(request.POST)
        return render(request, 'members/findID.html', {'form':form})


'''
def logout(request):
    django_logout(request)
    return redirect('index')

'''
def profile(request):
    print(request.user)
    member = get_object_or_404(User, username=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            return redirect('members:profile')
    else:
        form = ProfileForm(instance=member)

    return render(request, 'members/profile.html', {'form':form})

def delete(request):

members/templates/members/add_address.html
{% extends 'base.html' %}
{% block title %}My Page{% endblock %}
{% block content %}
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

<script language="JavaScript">
        function openZipSearch() {
	        new daum.Postcode({
		        oncomplete: function(data) {
			        $('[name=zip]').val(data.zonecode); // 우편번호 (5자리)
			        $('[name=addr1]').val(data.address);
			        $('[name=addr2]').val(data.buildingName);
		        }
	        }).open();
        }
</script>

    <nav class="navbar navbar-default">
      <div class="container">
        배송지추가<br>
          <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}

            <p>
        {{ form.as_p}}
            </p>

        <button type="button" style="width:60px; height:32px;" onclick="openZipSearch()">검색</button><br>
        <button type="submit" class="save btn btn-default">추가하기</button>
          </form>
      </div>
    </nav>


{% endblock %}

members/templates/members/confirmID.html
{% extends 'base.html' %}
{% block title %}My Page{% endblock %}
{% block content %}

ID 찾기

{{member.email}}
{{member.username}}

{% endblock %}

members/templates/members/coupon.html
{% extends './mypage.html' %}
{% block title %}Coupon Page{% endblock %}
{% block content %}
    <h2>사용 가능 쿠폰</h2>
    <h3>{{ coupons|length }} 개</h3>
    {% for coupon in coupons %}
        {{ coupon.coupon.name }}
        {{ coupon.coupon.discount }}
        {{ coupon.coupon.expiration_date }}
        {{ coupon.coupon.minimum_price }}
        <br>
    {% endfor %}
    <h2>쿠폰 등록</h2>
    <form action="{% url 'members:CouponRegister' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit"class="btn btn-outline-primary">쿠폰등록</button>
    </form>
{% endblock %}

members/templates/members/memberdelete.html
{% extends 'base.html' %}
{% block title %}My Page{% endblock %}
{% block content %}
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
            이유가 뭡니꽈??


            <form action="" method ="post">
                {% csrf_token%}
                <input type="submit" value="계정 삭제">
            </form>

        </ul>
      </div>
    </nav>
{% endblock %}

members/templates/members/signup.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}
{% block head_links %} 

<title>Signup</title>

{% endblock %}

{% block content %}
<div class="container-fluid">

 {% block messages %}
    {% if messages %}
    <div>
        <ul>
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
  {% endblock %}
  

<h3 class="h3" id="head_banner">{% trans "Sign Up" %}</h3>

<p class="exist_account_info">{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>.{% endblocktrans %}</p>

<form class="container-fluid text-center" id="signup_form" method="post" action="{% url 'members:signup' %}" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}



  {% if redirect_field_value %}


  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />

  {% endif %}

  <button class="btn btn-outline-primary btn-lg" type="submit">{% trans "Sign Up" %}</button>
</form>



</div>



<h1>SEND SMS!</h1>
<form action="" method="post" name="send">
    {% csrf_token %}
    <div>{{ send_form }}</div>
    <button type="button" id="send1" onclick="sending();" value="seend">전송하기</button>
</form>

<form action="" method="post" name="confirm">
    {% csrf_token %}
    <div>{{ confirm_form }}</div>
    <button type="submit">인증하기</button>
</form>

<script type="text/javascript">
function sending() {
    var send_form = document.send;
    if($('#id_msg_getter').val()){
        var value = $('#id_msg_getter').val();
        sessionStorage.setItem('sent',value);
        send_form.submit();
    //alert(value);
        return value;
    }
    //document.getElementById("id_msg_getter").setAttribute("value",value);
    //document.getElementById("divId").innerHTML += "<input type='text' name='' id=''/>";
}
if(sessionStorage.getItem('sent')!=null)
    document.getElementById("id_msg_getter").setAttribute("value",sessionStorage.getItem('sent'));

</script>

{% endblock %}

members/templates/members/test.html
{% extends 'base.html' %}

{% block content %}
<style>
    .outbox{
           width: 1310px;height: 970px; margin-top: -8px; background-color: #f1f3f5;
      }

    .mainbox{
          border: solid 1px white; width: 492px;height: 970px; margin-top: -8px; background-color: white;
      }
     .email_w
      {
        object-fit: contain;font-family: NanumGothic;font-size: 12px;font-weight: bold;font-style: normal;font-stretch: normal;line-height: 1.17;letter-spacing: -0.24px;text-align: center;color: #070707;float:left; margin-left: 18px;margin-top: -3px;
      }
    #send1{
          display:block; font-family: NanumGothic;font-size: 15px;font-weight: bold;font-style: normal;font-stretch: normal;letter-spacing: -0.3px;text-align:center;line-height: 38px; text-decoration: none;color: white;
        top: 500px;
        left: 700px;
    }
    #confirm1{
          display:block; font-family: NanumGothic;font-size: 15px;font-weight: bold;font-style: normal;font-stretch: normal;letter-spacing: -0.3px;text-align:center;line-height: 38px; text-decoration: none;color: white;
         top: 572px;
        left: 700px;
    }
      .login{
          position: absolute;
        width: 100px;height: 38px;background-color:#32b09d;border-radius: 4px;

      }
     .login2{
          position: absolute;
        width: 100px;height: 38px;background-color:#32b09d;border-radius: 4px;

      }
</style>
 <center><div class="outbox">
 <center><div class="mainbox">
<h3>인증하기</h3>
     <br>
<form action="" method="post" name="send">
    {% csrf_token %}
    <div class="email_w">{{ send_form }}</div>
    <button type="button" class= "login" id="send1" onclick="sending();" value="seend">전송하기</button>
</form>
     <br><br><br>
<form action="" method="post" name="confirm">
    {% csrf_token %}
    <div class="email_w">{{ confirm_form }}</div>
    <button class= "login2" id="confirm1" type="submit">인증하기</button>
</form>

<script type="text/javascript">
function sending() {
    var send_form = document.send;
    if($('#id_msg_getter').val()){
        var value = $('#id_msg_getter').val();
        sessionStorage.setItem('sent',value);
        send_form.submit();
    //alert(value);
        return value;
    }
    //document.getElementById("id_msg_getter").setAttribute("value",value);
    //document.getElementById("divId").innerHTML += "<input type='text' name='' id=''/>";
}
if(sessionStorage.getItem('sent')!=null)
    document.getElementById("id_msg_getter").setAttribute("value",sessionStorage.getItem('sent'));

</script>

{% endblock %}

members/templates/members/test2.html
{% extends 'base.html' %}

{% block content %}
<h1>SENT SMS!</h1>
<h2>보내기 완료</h2>

{% endblock %}

members/templates/members/update_address.html
{% extends 'base.html' %}
{% block title %}My Page{% endblock %}
{% block content %}
<script src="https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js"></script>

<script language="JavaScript">
        function openZipSearch() {
	        new daum.Postcode({
		        oncomplete: function(data) {
			        $('[name=zip]').val(data.zonecode); // 우편번호 (5자리)
			        $('[name=addr1]').val(data.address);
			        $('[name=addr2]').val(data.buildingName);
		        }
	        }).open();
        }
</script>
 <style>
     #id_addr_name,#id_phone{
      border: solid 1px #dee2e6; width: 550px;height: 38px;margin-top: 0px; border-radius: 4px; margin-right: 8px;font-family: NanumGothic;font-size: 17px;font-weight: normal;font-style: normal;font-stretch: normal;line-height: 1.18;letter-spacing: -0.34px;text-align: left;color: #070707;
    }
     .pw_w
    {
      object-fit: contain;font-family: NanumGothic;font-size: 14px;font-weight: bold;font-style: normal;font-stretch: normal;line-height: 1.17;letter-spacing: -0.24px;text-align: center;color: #070707;float:left;
    }
     .b_modify{
      width: 140px;height: 46px;object-fit: contain;border-radius: 33px;border: solid 1px #32b09b; background-color: white; font-family: NanumGothic;font-size: 17px;font-weight: normal;line-height: 1.18;letter-spacing: -0.34px;text-align: center;color: #32b09b;cursor: pointer; margin-left: 15px;
    }
     .b_add{
      width: 120px;height: 43px;object-fit: contain;border-radius: 4px;border: solid 1px #707070;background-color: #ffffff;
      font-family: NanumGothic;font-size: 16px;font-weight: bold;line-height: 1.19;letter-spacing: -0.32px;text-align: center;color: #707070; float:left; margin-left: 7px; cursor: pointer;
    }
    .title{
      font-family: NanumGothic;font-size: 26px;font-weight: bold;line-height: 1.15;letter-spacing: -0.52px;text-align: center;color: #070707;width: 150px; height: 30px;
    }
    .star{
      font-family: NanumGothic;font-size: 14px;font-weight: bold;color:#32d09b;float:left;margin-left: 3px;
    }
     #id_zip{
      border: solid 1px #dee2e6; background-color: #f1f3f5; width: 224px;height: 38px;;border-radius: 4px; margin-top: 3px; float:left;
    }
    #id_addr1,#id_addr2{
      border: solid 1px #dee2e6;width: 550px;height: 38px;;border-radius: 4px; margin-top: 5px;
    }
 </style>
     <div style="margin-left:500px; width:550px;">
     <center><h2 class="title">배송지 편집</h2></center>
          <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="pw"><br>
            <div class="pw_w">배송지명</div>
            <br>
            <div class="input_window1">{{form.addr_name}}</div>
            </div>
            <div class="pw"><br>
            <div class="pw_w">연락처</div>
            <div class="star">*</div>
            <br>
            <div class="input_window1">{{form.phone}}</div>
            </div>
            <div class="pw"><br>
            <div class="pw_w">주소</div>
            <div class="star">*</div><br>
            </div>
            <div class="input_window3">{{form.zip}}</div>
              <button type="button" name="button" class="b_add" onclick="openZipSearch()">주소 찾기</button><br><br>

            <div class="input_window4" style="background-color: #f1f3f5;">{{form.addr1}}</div>
            <div class="input_window4" >{{form.addr2}}</div>
            <br><br>
            <button type="submit" class="b_modify" >수정하기</button>
          </form>
      </div>



{% endblock %}

members/templates/members/wrongID.html
{% extends 'base.html' %}
{% block title %}My Page{% endblock %}
{% block content %}

ID 찾기<br>

등록된 ID가 없습니다.<br>

    <a class="btn btn-outline-dark" href="/accounts/signup">회원가입</a>
    <a class="btn btn-outline-dark" href="{% url 'members:findID' %}">ID 찾기</a>

{% endblock %}