cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='product_add'),
    path('remove/<product_id>/<int:option_id>', remove, name='product_remove'),
]

shop/urls.py
from django.urls import path
from django.urls import re_path
from .views import *
from django.views.generic import TemplateView

app_name = 'shop'

urlpatterns = [

    path('', home, name='product_all'),
    path('search/', search, name='search'),
    path('nonmember/', nonmember, name='nonmember'),
    path('searchOrder/',searchOrder, name='searchOrder'),
    path('best_item/', best_item, name="best_item"),
    path('new_item/', new_item, name="new_item"),
    path('frugal_shopping/', frugal_shopping, name="frugal_shopping"),
    path('qufide_recommend', qufide_recommend, name="qufide_recommend"),
    path('recommend/', recommend, name='recommend'),
    path('event/', event, name="event"),
    path('event/<slug:event_slug>', event_detail, name="event_detail"),
    path('recipe/', recipe, name="recipe"),
    path('recipe/<int:id>/<recipe_slug>', recipe_detail, name="recipe_detail"),
    path('collection/', collection, name='collection'),
    path('collection/<slug:collection_slug>', collection_detail, name="collection_detail"),
    path('commentselect/', comment_select, name='comment_select'),
    path('<slug:category_slug>/', category, name='category'),  # 카테고리 선택
    path('comment/<int:id>/', comment_detail, name='comment_detail'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),  # 상품 상세 페이지
    path('<int:id>/<product_slug>/comment/', comment, name='comment'),
    path('comment/<int:id>/delete/', delete_comment, name="delete_comment"),
    path('comment/<int:id>/update/', update_comment, name="update_comment"),

]

shop/forms.py
from .models import Product,Comment,Collection,Option
from django import forms
from coupon.models import *

from django.conf import settings
INTEGER_CHOICES= [tuple([x,x]) for x in range(0,6)]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_text', 'like', 'comment_image']
        widget = {
            'like' : forms.Select(attrs=INTEGER_CHOICES)
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args,**kwargs)
        self.fields['comment_text'].label = "댓글"
        self.fields['comment_image'].required = False
        #file값이 없더라도 view에서 유효성 검사에서 오류를 발생시키지 않도록 해준다.

class OptionForm(forms.ModelForm):

    class Meta:
        model = Option
        fields = ['name', 'add_price', 'stock']

    def __init__(self, *args, **kwargs):
        super(OptionForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "옵션"

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import AddProductForm
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from order.models import *
# ------- 인증번호 -------
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from . import models as m
# ------------------

from django.db.models import Count
from django.db.models import Max, Min
from django.db.models import Q
from datetime import datetime, timedelta



def category(request, category_slug=None): # 카테고리 페이지
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)
    results = Product.objects.filter(available_display=True)

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        if current_category.is_child_node():
            results = products.filter(categories=current_category)
        else:
            results = products.filter(categories=current_category)
            for slug in current_category.get_descendants(include_self=True):
                results = results | products.filter(categories=slug)

    descendant_categories = current_category.get_descendants(include_self=False)

    order = ''
    if request.method == "GET":
        if 'orderby' in request.GET:
            order = request.GET['orderby']
            print (order)

        if order == 'review':
            results = results.annotate(comment_count=Count("comment")).order_by("-comment_count")
            context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
            return render(request,'shop/list.html', context)
        elif order == 'like':
            results = results.annotate(comment_like=Max("comment__like")).order_by('-comment_like')
            context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
            return render(request,'shop/list.html', context)
        elif order == 'lowprice':
            results = results.order_by('price')
            context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
            return render(request,'shop/list.html', context)
        elif order == 'highprice':
            results = results.order_by('-price')
            context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
            return render(request,'shop/list.html', context)
        elif order == 'date':
            results = results.order_by('created')
            context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
            return render(request,'shop/list.html', context)
        else:
            results = results.order_by('-count_order')
            context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
            return render(request, 'shop/list.html', context)

    results = results.order_by('-count_order')
    context = {'current_category': current_category, 'categories': categories, 'products': results, 'descendant_categories':descendant_categories}
    return render(request,'shop/list.html', context)


def product_detail(request, id, product_slug=None): # 제품 상세 뷰
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=id, slug=product_slug)

    relative_products = Product.objects.filter(group=product.group).exclude(slug=product_slug)
    recipes = Recipe.objects.filter(products=product)


    #comment 부분
    comments = Comment.objects.filter(product=product)
    if request.method == "POST":
        comment_form = CommentForm(request.POST, request.FILES)
        comment_form.instance.author = request.user.id
        comment_form.instance.product_slug = product_slug
        if comment_form.is_valid():
            comment = comment_form.save()
        # models.py에서 document의 related_name을 comments로 해놓았다.
    options = Option.objects.filter(product=product)
    comment_form = CommentForm()
    options = Option.objects.filter(product=product)
    for option in options:
        add_to_cart = AddProductForm(initial={'quantity': 1})

    order=''
    if request.method == "GET":
        if 'orderby' in request.GET:
            order = request.GET['orderby']

        if order == 'like':
            comments = comments.order_by('-like')
            return render(request, 'shop/detail.html',
                          {'product': product, 'add_to_cart': add_to_cart, 'relative_products': relative_products,
                           'comments': comments, 'comment_form': comment_form, 'options': options})
        elif order == 'date':
            comments = comments.order_by('-comment_created')
            return render(request, 'shop/detail.html',
                          {'product': product, 'add_to_cart': add_to_cart, 'relative_products': relative_products,
                           'comments': comments, 'comment_form': comment_form, 'options': options})


    comments = comments.order_by('-like')
    return render(request, 'shop/detail.html', {'product':product, 'add_to_cart':add_to_cart, 'relative_products': relative_products,
                                                'comments':comments, 'comment_form':comment_form, 'options':options})




def comment(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    comments = Comment.objects.filter(product=product)
    if request.method == "POST":
        
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = Product.objects.get(id=id)
            comment.author = request.user
            comment.save()
            return redirect('shop:comment', id, product_slug)
    else:
        form = CommentForm()

    order = ''
    if request.method == "GET":
        if 'orderby' in request.GET:
            order = request.GET['orderby']

        if order == 'date':
            comments = comments.order_by('-comment_created')
            return render(request, 'shop/comment.html', {'form': form, 'comments':comments, 'product':product})
        else:
            comments = comments.order_by('-like')
            return render(request, 'shop/comment.html', {'form': form, 'comments':comments, 'product':product})

    comments = comments.order_by('-like')

    return render(request, 'shop/comment.html', {'form': form, 'comments':comments, 'product':product})



def comment_detail(request, id):
    comment = Comment.objects.get(id=id)
    form = CommentForm()

    return render(request, 'shop/comment_detail.html', {'comment':comment, 'form':form})



def delete_comment(request, id):

    comment = Comment.objects.get(id=id)
    product = get_object_or_404(Product, slug=comment.product.slug)

    if request.user != comment.author and not request.user.is_staff:
        messages.warning(request, '권한 없음')
        return redirect('shop:comment', product.id, product.slug)

    if request.method == "POST":
        comment.delete()
        return redirect('shop:comment', product.id, product.slug)
    else:
        return render(request, 'shop/delete_comment.html', {'object':comment})



def update_comment(request, id):

    comment = Comment.objects.get(id=id)
    product = get_object_or_404(Product, slug=comment.product.slug)


    if request.user != comment.author:
        messages.warning(request, "권한 없음")
        return redirect('shop:comment', product.id, product.slug)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('shop:comment', product.id, product.slug)
    else:
        form = CommentForm(instance=comment)

    return render(request,'shop/update_comment.html', {'form':form})



def comment_select(request):
    comments = Comment.objects.all()

    if request.method == 'POST':
        select = request.POST.getlist('select')
        best_comments = Comment.objects.filter(id__in=select)
        false_comments = Comment.objects.all().exclude(id__in=select)
        for best_comment in best_comments:
            best_comment.best=True
            best_comment.save()
        for false_comment in false_comments:
            false_comment.best=False
            false_comment.save()

    return render(request, 'shop/`.html', {'comments': comments})



def home(request, category_slug=None) :
    categories = Category.objects.all()
    current_category = None

    banners = Banner.objects.all()
    comments = Comment.objects.filter(best=True)


    sale_products = Product.objects.exclude(sale_percent=0).order_by('-count_order')[:4]
    recommend_products = Product.objects.filter(recommend=1).order_by('-count_ordproducter')[:4]
    best_products = Product.objects.order_by('-count_order')[:4]
    best_comments = Comment.objects.filter(best=1)[:2]
    return render(request, 'shop/home.html',
              {'categories': categories, 'current_category': current_category, 'banners': banners,
               'comments': comments, 'sale_products': sale_products, 'recommend_products': recommend_products,
               'best_products': best_products, 'best_comments': best_comments})

def search(request, search_term = ''):
    products = Product.objects.all()
    categories = Category.objects.all()
    if 'search' in request.GET:
        search_term = request.GET['search']

shop/templates/shop/collection_detail.html
{% extends 'base.html' %}
{% block title %}Collection Detail Page{% endblock %}
{% block content %}
<div class="collection_detail">
    <img src="{{collection.title_image.url }}" alt="title_image">
</div>
    <p class="small_title">{{ collection.name }}</p>
    <div class="product_count">총 {{ product_count }}개</div>
    <ul class="card_list">
        {% for product in selected_products %}
            <li class="card_item">
                <a href="{{ product.get_absolute_url }}"><img class="image" src="{{product.image.url}}"></a>
                <strong class="name">{{ product.name }}</strong>
                <strong class="count_order">{{ product.count_order }}개</strong>
                <span><strong class="actual_price">
                    {% if product.sale_percent == 0 %}
                        <span>{{product.price}}원</span></strong>>
                    {% else %}
                        <script>var saled_price = {{product.price}}*(100-{{product.sale_percent}})/100;
                        document.write(Math.floor(saled_price));</script>원</strong>
                        <strong class="price"><strike>{{product.price}}</strike>원</strong>
                    {% endif %}
                    <div class="percent">{{ product.sale_percent }}%</div></span><br><br>
                <div class="tags" style="margin-top:-13px;">
                    {% load tagging_tags %}
                    {% tags_for_object product as tags %}
                    {% for tag in tags %}
                    <a href="/search/?search={{ tag.name }}" class="tag">{{tag.name}}</a>
                    {% endfor %}
                </div>
            </li>
        {% endfor %}
</ul>
    <style>
        .collection_detail img{width: 1194px;height: 500px;margin-left: 160px;}
    .small_title {font-family: NanumGothic;font-size: 26px;font-weight: 800;font-style: normal;font-stretch: normal;line-height: 1.15;
letter-spacing: normal;text-align: center;color: #32b09d;margin-top: 100px;}
    .product_count {font-family: NanumGothic;font-size: 12px;font-weight: 800;font-style: normal;font-stretch: normal;
    margin-left: 155px;margin-top: 20px;}
    .card_list{
      width: 80%;margin: 0 auto;display: flex;flex-wrap: wrap;
  }
.card_item{
    display: flex;flex-direction: column;flex: none;flex-basis: 25%;margin-top: 20px;padding: 0 7px;box-sizing: border-box;
  }
  .image{
      flex: flex;width: 268px; height: 270px;background-color: #dcdcdf;
  }
  .channel_list .name{
      flex: none;min-height: 0;margin-top: 8px;font-size: 16px;font-weight: bold;
  }
  .name{
      font-family: NanumGothic;font-size:16px;font-weight: bold;line-height: 1.19;letter-spacing: -0.32px;text-align: left;color: #070707;margin-top: 8px;
  }
  .count_order{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; margin-bottom: 6px; margin-top: 6px;
  }
  .actual_price{
     font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #303030;margin-left: -3px; float:left;
  }
  .price{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; float:left; margin-left: 0px; margin-top: 5px;
  }
.percent{
    font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #ef2f35; float:right;
}
.tag{
    font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: center;color: #32b09d;border: solid 1px #32b09d; background-color: #ffffff; padding:4px; text-decoration: none;
}
    </style>
{% endblock %}

shop/templates/shop/commentselect.html
{% extends 'base.html' %}
{% block title %}Comment_select{% endblock %}
{% block content %}



<div class="container">

        <h3> Comments </h3>
                    <!-- Single Comment -->

        <form action="{% url 'shop:comment_select' %}" method="post" name="checkbox">
                        <input type="checkbox" onclick="check_all()" id="allCheck"> <label>Check ALL</label>
                        <br />
                       {% for comment in comments %}
                            {% if comment.best == True %}
                                <input type="checkbox" name="select" value={{comment.id}} checked>
                            {% else %}
                                <input type="checkbox" name="select" value={{comment.id}}>
                            {% endif %}
                            <label><b>{{comment}}<a href="{% url 'shop:comment_detail' comment.id %}" class="mt-0"></b></label><br />
                            {% if comment.comment_image.url != None %}
                            <img src="{{comment.comment_image.url}}" width="10%">
                            {% endif %}
                            {% if comment.comment_image2.url != None %}
                                <img src="{{comment.comment_image2.url}}" width="10%">
                            {% endif %}
                            {% if comment.comment_image3.url != None %}
                                <img src="{{comment.comment_image3.url}}" width="10%">
                            {% endif %}                                <div class="media-body">
                                <h5 class="mt-0">작성자: {{comment.author}}</h5>
                                <h5 class="mt-0">품목: {{comment.product.name}}</h5>
                                <h5 class="mt-0">내용: {{comment.comment_text}}</h5>
                                </div>
                            <br><br><br>
                        {% endfor %}

                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary btn-sm" onclick="window.close()" value="적용하기">
        </form>
</div>

<script>
function check_all() {
    if($("#allCheck").prop("checked")) {
        for(i=0; i < checkbox.select.length; i++) {
            checkbox.select[i].checked = true;
        }
    }else{
        for(i=0; i < checkbox.select.length; i++) {
            checkbox.select[i].checked = false;
        }
    }
}
</script>

{% endblock %}

shop/templates/shop/event.html
{% extends 'base.html' %}
{% block title %}Event Page{% endblock %}
{% block content %}
    <p class="small_title">이벤트</p>
    <div class="events">
    {% for event in events %}
        <a href="{{ event.get_absolute_url }}"><img class="title_image" src="{{ event.title_image.url }}"></a>
    {% endfor %}
    </div>
    <style>
    .small_title{
font-family: NanumGothic;font-size: 26px;font-weight: 800;font-style: normal;font-stretch: normal;line-height: 1.15;
letter-spacing: normal;text-align: center;color: #32b09d;margin-top: 100px;
}
    .events {
        margin-left: 150px;margin-top: 90px;
    }
    .title_image {
        width: 570px;height: 570px;margin-right: 11px;margin-bottom: 12px;}
    </style>
{% endblock %}

shop/templates/shop/event_detail.html
{% extends 'base.html' %}
{% block title %}Event Detail Page{% endblock %}
{% block content %}
    <div><img class="event_content" src="{{ event.content.url }}"></div>
<style>
.event_content{
    width: 1167px;height:auto;margin-left: 90px;margin-top: 10px;
}
</style>
{% endblock %}

shop/templates/shop/frugal_shopping.html
{% extends 'base.html' %}
{% block title %}Frugal Shopping Page{% endblock %}
{% block content %}
    {% load static %}
    <p class="small_title">초특가 할인<img src="{% static "image/확성기.PNG" %}"></p>
    <div class="product_count">총 {{ products|length }}개</div>
<ul class="card_list">
        {% for product in products %}
            <li class="card_item">
                <a href="{{ product.get_absolute_url }}"><img class="image" src="{{product.image.url}}"></a>
                <strong class="name">{{ product.name }}</strong>
                <strong class="count_order">{{ product.count_order }}개</strong>
                <span><strong class="actual_price">
                    {% if product.sale_percent == 0 %}
                        <span>{{product.price}}원</span></strong>>
                    {% else %}
                        <script>var saled_price = {{product.price}}*(100-{{product.sale_percent}})/100;
                        document.write(Math.floor(saled_price));</script>원</strong>
                        <strong class="price"><strike>{{product.price}}</strike>원</strong>
                    {% endif %}
                    <div class="percent">{{ product.sale_percent }}%</div></span><br><br>
                <div class="tags" style="margin-top:-13px;">
                    {% load tagging_tags %}
                    {% tags_for_object product as tags %}
                    {% for tag in tags %}
                    <a href="/search/?search={{ tag.name }}" class="tag">{{tag.name}}</a>
                    {% endfor %}
                </div>
            </li>
        {% endfor %}
    </ul>
    <style>
    .small_title{
font-family: NanumGothic;font-size: 26px;font-weight: 800;font-style: normal;font-stretch: normal;line-height: 1.15;
letter-spacing: normal;text-align: center;color: #32b09d;margin-top: 100px;
}
    .product_count {font-family: NanumGothic;font-size: 12px;font-weight: 800;font-style: normal;font-stretch: normal;
    margin-left: 155px;margin-top: 20px;}
    .card_list{
      width: 80%;margin: 0 auto;display: flex;flex-wrap: wrap;
  }
.card_item{
    display: flex;flex-direction: column;flex: none;flex-basis: 25%;margin-top: 20px;padding: 0 7px;box-sizing: border-box;
  }
  .image{
      flex: flex;width: 268px; height: 270px;background-color: #dcdcdf;
  }
  .channel_list .name{
      flex: none;min-height: 0;margin-top: 8px;font-size: 16px;font-weight: bold;
  }
  .name{
      font-family: NanumGothic;font-size:16px;font-weight: bold;line-height: 1.19;letter-spacing: -0.32px;text-align: left;color: #070707;margin-top: 8px;
  }
  .count_order{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; margin-bottom: 6px; margin-top: 6px;
  }
  .actual_price{
     font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #303030;margin-left: -3px; float:left;
  }
  .price{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; float:left; margin-left: 0px; margin-top: 5px;
  }
.percent{
    font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #ef2f35; float:right;
}
.tag{
    font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: center;color: #32b09d;border: solid 1px #32b09d; background-color: #ffffff; padding:4px; text-decoration: none;
}
    </style>
{% endblock %}

shop/templates/shop/new_item.html
{% extends 'base.html' %}
{% block title %}New Item Page{% endblock %}
{% block content %}
    <p class="small_title">신상품</p>
    <div class="product_count">총 {{ product_count }}개</div>
<ul class="card_list">
        {% for product in products %}
            <li class="card_item">
                <a href="{{ product.get_absolute_url }}"><img class="image" src="{{product.image.url}}"></a>
                <strong class="name">{{ product.name }}</strong>
                <strong class="count_order">{{ product.count_order }}개</strong>
                <span><strong class="actual_price">
                    {% if product.sale_percent == 0 %}
                        <span>{{product.price}}원</span></strong>>
                    {% else %}
                        <script>var saled_price = {{product.price}}*(100-{{product.sale_percent}})/100;
                        document.write(Math.floor(saled_price));</script>원</strong>
                        <strong class="price"><strike>{{product.price}}</strike>원</strong>
                    {% endif %}
                    <div class="percent">{{ product.sale_percent }}%</div></span><br><br>
                <div class="tags" style="margin-top:-13px;">
                    {% load tagging_tags %}
                    {% tags_for_object product as tags %}
                    {% for tag in tags %}
                    <a href="/search/?search={{ tag.name }}" class="tag">{{tag.name}}</a>
                    {% endfor %}
                </div>
            </li>
        {% endfor %}
</ul>
    <style>
    .small_title{
font-family: NanumGothic;font-size: 26px;font-weight: 800;font-style: normal;font-stretch: normal;line-height: 1.15;
letter-spacing: normal;text-align: center;color: #32b09d;margin-top: 100px;
}
    .product_count {font-family: NanumGothic;font-size: 12px;font-weight: 800;font-style: normal;font-stretch: normal;
    margin-left: 155px;margin-top: 20px;}
    .card_list{
      width: 80%;margin: 0 auto;display: flex;flex-wrap: wrap;
  }
.card_item{
    display: flex;flex-direction: column;flex: none;flex-basis: 25%;margin-top: 20px;padding: 0 7px;box-sizing: border-box;
  }
  .image{
      flex: flex;width: 268px; height: 270px;background-color: #dcdcdf;
  }
  .channel_list .name{
      flex: none;min-height: 0;margin-top: 8px;font-size: 16px;font-weight: bold;
  }
  .name{
      font-family: NanumGothic;font-size:16px;font-weight: bold;line-height: 1.19;letter-spacing: -0.32px;text-align: left;color: #070707;margin-top: 8px;
  }
  .count_order{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; margin-bottom: 6px; margin-top: 6px;
  }
  .actual_price{
     font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #303030;margin-left: -3px; float:left;
  }
  .price{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; float:left; margin-left: 0px; margin-top: 5px;
  }
.percent{
    font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #ef2f35; float:right;
}
.tag{
    font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: center;color: #32b09d;border: solid 1px #32b09d; background-color: #ffffff; padding:4px; text-decoration: none;
}
    </style>
{% endblock %}

shop/templates/shop/qufide_recommend.html
{% extends 'base.html' %}
{% block title %}Qufide Recommend{% endblock %}
{% block content %}
        {% load static %}
    <p class="small_title">큐피드 추천<img src="{% static "image/그룹 70.png" %}"></p>
    <div class="product_count">총 {{ product_count }}개</div>
<ul class="card_list">
        {% for product in products %}
            <li class="card_item">
                <img class="image" src="{{product.image.url}}">
                <strong class="name">{{ product.name }}</strong>
                <strong class="count_order">{{ product.count_order }}개</strong>
                <span><strong class="actual_price">
                    {% if product.sale_percent == 0 %}
                        <span>{{product.price}}원</span></strong>>
                    {% else %}
                        <script>var saled_price = {{product.price}}*(100-{{product.sale_percent}})/100;
                        document.write(Math.floor(saled_price));</script>원</strong>
                        <strong class="price"><strike>{{product.price}}</strike>원</strong>
                    {% endif %}
                    <div class="percent">{{ product.sale_percent }}%</div></span><br><br>
                <div class="tags" style="margin-top:-13px;">
                    {% load tagging_tags %}
                    {% tags_for_object product as tags %}
                    {% for tag in tags %}
                    <a href="/search/?search={{ tag.name }}" class="tag">{{tag.name}}</a>
                    {% endfor %}
                </div>
            </li>
        {% endfor %}
</ul>
    <style>
    .small_title{
font-family: NanumGothic;font-size: 26px;font-weight: 800;font-style: normal;font-stretch: normal;line-height: 1.15;
letter-spacing: normal;text-align: center;color: #32b09d;margin-top: 100px;
}
    .product_count {font-family: NanumGothic;font-size: 12px;font-weight: 800;font-style: normal;font-stretch: normal;
    margin-left: 155px;margin-top: 20px;}
    .card_list{
      width: 80%;margin: 0 auto;display: flex;flex-wrap: wrap;
  }
.card_item{
    display: flex;flex-direction: column;flex: none;flex-basis: 25%;margin-top: 20px;padding: 0 7px;box-sizing: border-box;
  }
  .image{
      flex: flex;width: 268px; height: 270px;background-color: #dcdcdf;
  }
  .channel_list .name{
      flex: none;min-height: 0;margin-top: 8px;font-size: 16px;font-weight: bold;
  }
  .name{
      font-family: NanumGothic;font-size:16px;font-weight: bold;line-height: 1.19;letter-spacing: -0.32px;text-align: left;color: #070707;margin-top: 8px;
  }
  .count_order{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; margin-bottom: 6px; margin-top: 6px;
  }
  .actual_price{
     font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #303030;margin-left: -3px; float:left;
  }
  .price{
     font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: left;color: #909090; float:left; margin-left: 0px; margin-top: 5px;
  }
.percent{
    font-family: NanumGothic;font-size: 20px;font-weight: 800;line-height: 1.15;letter-spacing: -0.4px;text-align: left;color: #ef2f35; float:right;
}
.tag{
    font-family: NanumGothic;font-size: 12px;font-weight: bold;line-height: 1.17;letter-spacing: -0.24px;text-align: center;color: #32b09d;border: solid 1px #32b09d; background-color: #ffffff; padding:4px; text-decoration: none;
}
    </style>
{% endblock %}

shop/templates/shop/update_comment.html
{% extends 'base.html' %}


{% block content %}
<h1>수정 페이지</h1>
<form action="" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
         {{form.as_table}}
    </table>
    <input type="submit" value="Write">

</form>

{% endblock %}